"""
warper.py - Rockit Audio Warping Module

This script processes raw audio files (like those generated by Suno AI) and
time-stretches them to a fixed, mathematical BPM grid. This is critical for
rhythm games where fluctuating tempos cause the beatmap notes to drift out
of sync with the audio.

It uses:
1. Demucs: To isolate the drum stems, removing melodic interference.
2. Librosa: To detect the precise beat onset timings from the isolated drums.
3. PyRubberband: To dynamically stretch/compress the original audio between
   those beat onsets, forcing the track onto a perfect global grid.
4. ffmpeg loudnorm: To master the warped output to a consistent streaming-safe
   loudness target.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

import librosa
import numpy as np
import soundfile as sf
import pyrubberband as pyrb

DEFAULT_TARGET_LUFS = -14.0
DEFAULT_TRUE_PEAK = -1.0
DEFAULT_LOUDNESS_RANGE = 11.0


def _require_ffmpeg():
    if shutil.which("ffmpeg") is None:
        raise RuntimeError("ffmpeg not found. Post-warp mastering requires ffmpeg on PATH.")


def _extract_loudnorm_stats(stderr_text):
    matches = re.findall(r"\{\s*\"input_i\"\s*:.*?\}", stderr_text, re.DOTALL)
    if not matches:
        raise RuntimeError("ffmpeg loudnorm output did not include parseable measurement stats.")

    try:
        return json.loads(matches[-1])
    except json.JSONDecodeError as exc:
        raise RuntimeError("ffmpeg loudnorm measurement JSON could not be parsed.") from exc


def _measure_loudness(input_file, target_lufs, true_peak, loudness_range):
    command = [
        "ffmpeg",
        "-hide_banner",
        "-nostats",
        "-i",
        input_file,
        "-af",
        (
            f"loudnorm=I={target_lufs}:TP={true_peak}:LRA={loudness_range}:"
            "print_format=json"
        ),
        "-f",
        "null",
        "-",
    ]

    result = subprocess.run(
        command,
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg loudnorm analysis failed with exit code {result.returncode}.")

    return _extract_loudnorm_stats(result.stderr)


def _build_loudnorm_filter(stats, target_lufs, true_peak, loudness_range):
    return (
        f"loudnorm=I={target_lufs}:TP={true_peak}:LRA={loudness_range}:"
        f"measured_I={stats['input_i']}:"
        f"measured_TP={stats['input_tp']}:"
        f"measured_LRA={stats['input_lra']}:"
        f"measured_thresh={stats['input_thresh']}:"
        f"offset={stats['target_offset']}:"
        "linear=true:print_format=summary"
    )


def master_audio(input_file, output_file, target_lufs=DEFAULT_TARGET_LUFS, true_peak=DEFAULT_TRUE_PEAK):
    _require_ffmpeg()

    print("Step 6: Measuring loudness for mastering...")
    stats = _measure_loudness(input_file, target_lufs, true_peak, DEFAULT_LOUDNESS_RANGE)
    print(f"Measured loudness: {stats['input_i']} LUFS")
    print(f"Measured true peak: {stats['input_tp']} dBTP")
    print(f"Step 7: Mastering to {target_lufs} LUFS / {true_peak} dBTP...")

    command = [
        "ffmpeg",
        "-y",
        "-hide_banner",
        "-nostats",
        "-i",
        input_file,
        "-af",
        _build_loudnorm_filter(stats, target_lufs, true_peak, DEFAULT_LOUDNESS_RANGE),
    ]

    ext = os.path.splitext(output_file)[1].lower()
    if ext == ".wav":
        command.extend(["-c:a", "pcm_s16le"])
    elif ext == ".ogg":
        command.extend(["-c:a", "libvorbis", "-q:a", "6"])
    else:
        command.extend(["-c:a", "libmp3lame", "-q:a", "2"])

    command.append(output_file)

    result = subprocess.run(
        command,
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg loudnorm mastering failed with exit code {result.returncode}.")


def warp_audio(
    input_file,
    output_file,
    target_bpm=None,
    target_lufs=DEFAULT_TARGET_LUFS,
    true_peak=DEFAULT_TRUE_PEAK,
):
    """
    Isolates drums, tracks beat onsets, and stretches the audio to a fixed BPM.

    Args:
        input_file (str): Path to the raw input audio file (.wav, .mp3, etc.).
        output_file (str): Path to save the normalized output audio.
        target_bpm (float, optional): The exact static BPM to force. If None,
                                      the overall estimated tempo is used.
    """
    input_file = os.path.abspath(input_file)
    output_file = os.path.abspath(output_file)

    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Input audio file not found: {input_file}")

    print(f"Input file: {input_file}")
    print(f"Output file: {output_file}")

    with tempfile.TemporaryDirectory(prefix="rockit-demucs-") as temp_dir:
        # 1. Stem Separation with Demucs
        print(f"[{os.path.basename(input_file)}] Step 1: Separating stems with Demucs...")
        print(f"Working directory: {temp_dir}")

        try:
            subprocess.run(["demucs", input_file, "-o", temp_dir, "-n", "htdemucs"], check=True)
        except FileNotFoundError as exc:
            raise RuntimeError("Demucs command not found. Install Demucs and ensure it is on PATH.") from exc
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(f"Demucs failed with exit code {exc.returncode}.") from exc

        # Find the drums.wav file
        base_name = os.path.splitext(os.path.basename(input_file))[0]
        drums_path = os.path.join(temp_dir, "htdemucs", base_name, "drums.wav")

        if not os.path.exists(drums_path):
            raise FileNotFoundError(f"Drums stem not found at {drums_path}")

        # 2. Beat Detection with Librosa
        print("Step 2: Detecting beats on isolated drums stem...")
        y_drums, sr = librosa.load(drums_path, sr=None)
        tempo, beat_frames = librosa.beat.beat_track(y=y_drums, sr=sr)

        tempo_val = float(np.mean(tempo))
        if not np.isfinite(tempo_val) or tempo_val <= 0:
            raise RuntimeError(f"Detected invalid tempo: {tempo_val}")

        if target_bpm is None:
            target_bpm = round(tempo_val)

        if target_bpm <= 0:
            raise ValueError(f"Target BPM must be positive. Received: {target_bpm}")

        print(f"Detected tempo: {tempo_val:.2f} BPM")
        print(f"Target BPM: {target_bpm}")

        beat_times = librosa.frames_to_time(beat_frames, sr=sr)

        if len(beat_times) == 0:
            raise RuntimeError("No beats detected in the track.")

        # 3. Create Time Map for PyRubberband (In Audio Sample Frames)
        print("Step 3: Calculating time map for strictly locked BPM grid...")
        time_map = []

        # Load original audio in stereo early so we have sr_full and y_full length
        print("Loading full audio track for stretching...")
        y_full, sr_full = librosa.load(input_file, sr=None, mono=False)

        # PyRubberband expects shape (samples, channels)
        if y_full.ndim == 2 and y_full.shape[0] < y_full.shape[1]:
            y_full = y_full.T

        beat_samples = [int(round(t * sr_full)) for t in beat_times]

        if beat_samples[0] > 0:
            time_map.append((0, 0))

        current_target_sample = beat_samples[0]
        time_map.append((beat_samples[0], current_target_sample))

        beat_length_target_samples = int(round((60.0 / target_bpm) * sr_full))
        beat_length_source_sec = 60.0 / tempo_val

        # Lock each detected beat to the mathematical grid in exact samples
        for i in range(1, len(beat_times)):
            source_sample = beat_samples[i]
            delta_source_sec = beat_times[i] - beat_times[i - 1]

            # Calculate how many beats this delta most likely represents
            num_beats = round(delta_source_sec / beat_length_source_sec)
            if num_beats < 1:
                num_beats = 1

            delta_target_samples = num_beats * beat_length_target_samples
            current_target_sample += delta_target_samples

            time_map.append((source_sample, current_target_sample))

        # 4. Apply Time Map to Original Audio
        print("Step 4: Applying Rubberband time-stretching to original audio...")
        total_samples = len(y_full)

        # Add tail end to the time map to match strictly len(y_full) as required by pyrubberband
        if total_samples > time_map[-1][0]:
            tail_delta_samples = total_samples - time_map[-1][0]
            ratio = beat_length_target_samples / (beat_length_source_sec * sr_full)
            tail_target_delta = int(round(tail_delta_samples * ratio))
            time_map.append((total_samples, time_map[-1][1] + tail_target_delta))
        elif total_samples < time_map[-1][0]:
            time_map = [t for t in time_map if t[0] < total_samples]
            time_map.append((total_samples, time_map[-1][1]))

        y_stretched = pyrb.timemap_stretch(y_full, sr_full, time_map)

        # 5. Export the stretched intermediate before mastering.
        print("Step 5: Exporting stretched intermediate WAV...")
        os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)

        temp_wav = os.path.join(temp_dir, "stretched-intermediate.wav")
        sf.write(temp_wav, y_stretched, sr_full, format="WAV", subtype="PCM_16")

        master_audio(temp_wav, output_file, target_lufs=target_lufs, true_peak=true_peak)

    print(f"Success! Audio strictly locked to {target_bpm} BPM.")
    print(f"Mastered to {target_lufs} LUFS / {true_peak} dBTP.")
    print(f"Final output: {output_file}")
    return output_file


def main(argv=None):
    parser = argparse.ArgumentParser(description="Warp fluctuating AI audio to a fixed BPM grid.")
    parser.add_argument("input", help="Path to input audio (.wav/.mp3)")
    parser.add_argument("output", help="Path to output audio")
    parser.add_argument("--bpm", type=float, default=None, help="Target fixed BPM (default: intelligently rounded)")
    parser.add_argument(
        "--lufs",
        type=float,
        default=DEFAULT_TARGET_LUFS,
        help=f"Integrated loudness target in LUFS (default: {DEFAULT_TARGET_LUFS})",
    )
    parser.add_argument(
        "--true-peak",
        type=float,
        default=DEFAULT_TRUE_PEAK,
        help=f"True peak ceiling in dBTP (default: {DEFAULT_TRUE_PEAK})",
    )

    args = parser.parse_args(argv)

    try:
        warp_audio(args.input, args.output, args.bpm, args.lufs, args.true_peak)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
